version: 0.0
os: linux
files:
  - source: target/02-Maven-WebApp.war
    destination: /opt/tomcat/apache-tomcat-9.0.93/webapps

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root
